server:
  port: 9005
spring:
  thymeleaf:
    cache: false
  application:
    name: UserWeb4

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka, http://localhost:10087/eureka


  #开启Spring Cloud的重试功能
  cloud:
    loadbalancer:
      retry:
        enabled: true
USERPROVIDER:
  ribbon:
    #配置指定服务的负载均衡策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    # 是否对所有操作都进行重试
    OkToRetryOnAllOperations: true
    # 切换实例的重试次数
    MaxAutoRetriesNextServer: 1
    # 对当前实例的重试次数
    MaxAutoRetries: 1
#设定Hystrix熔断超时时间 ，理论上熔断时间应该大于总连接超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
# 开启Feign的熔断功能
feign:
  hystrix:
    enabled: true



